
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v6

      - name: 📂 Sync files
        uses: ./
        with:
        server: ftp.entercel.com
        username: enterce1_admin@entercel.com
        password: M@ypassq1212
  
